
language: r
sudo: false
cache: packages

r_binary_packages:
#   # install locally to avoid rev dep
#   - covr # code coverage check
  - lintr # code lint

r_github_packages:
  - HBGDki/travisDrat

after_success:
#   - Rscript -e 'covr::codecov()'
  - Rscript -e "travisDrat::deploy_drat('HBGDki/drat')"

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
    - travis

env:
  global:
    secure: "I8tVolqomuTXTbv3U5LfGfAxoDO7nFvD6b+0uqZs8NUkaOn/NN24gtlOln4ovQKWYKZqOQAS0C6q52WI+hwdiAPv9s5PSQZPqbE0aqVzUyQRM+NXMBS+S/E3g2TVIzpER5kLFK+j9FKjf6M6jlYJ4l6PTzzdvLkIvNfE1BXsCnldXwaKbMPOxeHd7I+nS+wj+Qirdv6wxxDkUFtQmyn062OBuoXGX7lg6Eq8nfX7JKRGwS7OegIDbtcbmuQYWRqdRy7Vjjx4pPABxgyiowFVsn3n4Z5YY1tGQwfhMuq7IICcLlQ00p6KyOp/ovg4p0gTOQY1u4ykrRMEoq/noPzCCmq7IkyF5+CHiV3wUaRRHc7cHr5Zh9NTZC9GpIua9Gfzq3Ne1JpaOm4ep1uAxbacac2SVEr6KWDw6wDuZerJGslns03fkICUgdP77Tv4IvZJHYRVC/K1fYfLvMx9MRYu3yEuqc89o26nPU0DoHTeHGwxdpH8oVQP7wYxh7nxGA0LUZb0Tjq7gAyMNM61PtV6vef9b1bQXlw5hkCv1ExZeaCeL9Ch5A/EYThgbWTqVOZBLUqqzCqjuunD6xBiC/7LxWNdyIF/kx+zjCJ3JL4NvWgfpTbfK/gQ0Lno3xXkW8Wek0bt0tZnh1f+9nBoXjxe4mmtgz1YBWA9Zs+wicOiw28="
