
language: r
sudo: false
cache: packages

r_binary_packages:
#   # install locally to avoid rev dep
#   - covr # code coverage check
  - lintr # code lint

r_github_packages:
  - HBGDki/travisDrat

after_success:
#   - Rscript -e 'covr::codecov()'
  - Rscript -e "travisDrat::deploy_drat('HBGDki/drat')"

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
    - travis
